#!/usr/bin/env ruby
# Copyright (c) 2008-2010, Edd Barrett <vext01@gmail.com>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 
# RBlatter
# $Id: rblatter,v 1.2 2011/03/08 00:09:42 edd Exp $
#
# == Synopsis
# RBlatter is a ruby script which allows you to add and subtract TeXmf
# subsets using the TeX Live TLPDB information. 
#

$RBLATTER_V = "$OpenBSD: rblatter,v 1.2 2011/03/08 00:09:42 edd Exp $"
$QUIET = true;
$FILEPREFIX = ""
$ARCH = "x86_64"
$MISSING_FILES = true
$ADD_DIRS = false

path = File.dirname $0
$: << path + "/lib"

require "options"
require "subsetshaper"
require "eqnparser"

# Parse args
# this +options+ Hash is just for review at this point,
# since the $GLOBALS are being used in the SubsetShaper
options = parse_args(ARGV)

# Checks
if !defined? $TLMASTER then
	puts "*error: no --tlmaster | -t defined";
	exit 1
end

if !defined? $OUTDIR then
	puts "*error: no --outdir | -o  defined";
	exit 1
end

if ARGV.length != 1
	puts "*error: no subset equation specified."
	exit 0
end

# Yoink equation as whats left of command line
$EQN = ARGV.shift

# Go!
shaper = SubsetShaper.new

if !$QUIET then
	puts "Job done!"
end
